spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/toDo}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true